#!/usr/bin/env python3

# --- LLM Inference Cost Model Parameters ---
# These are hypothetical costs, actual costs vary significantly by model,
# provider, and tier. They illustrate the 'token economics' concept.
COST_PER_INPUT_TOKEN = 0.0000015  # Example: $1.50 per 1 million input tokens
COST_PER_OUTPUT_TOKEN = 0.0000020 # Example: $2.00 per 1 million output tokens

# --- Simulation Parameters ---
# These parameters define the 'traffic profile' and model usage.
AVERAGE_PROMPT_TOKENS = 150       # Average number of tokens in user's prompt
AVERAGE_COMPLETION_TOKENS = 300   # Average number of tokens generated by the LLM
REQUESTS_PER_SECOND = 5           # Average number of inference requests per second
SIMULATION_DURATION_HOURS = 24    # How long to simulate (e.g., 1 hour, 24 hours)

def calculate_inference_cost(
    prompt_tokens: int,
    completion_tokens: int,
    rps: float,
    duration_hours: float,
    cost_input_token: float,
    cost_output_token: float
) -> dict:
    """
    Calculates the total inference cost for a given set of parameters.
    This function models the core concept of LLM inference cost based on token usage.
    """
    total_seconds = duration_hours * 3600
    total_requests = rps * total_seconds

    # Calculate total tokens processed over the simulation period
    # This highlights how prompt and completion lengths directly impact token count.
    total_input_tokens = total_requests * prompt_tokens
    total_output_tokens = total_requests * completion_tokens
    total_tokens = total_input_tokens + total_output_tokens

    # Calculate the cost based on token economics
    # Different costs for input vs. output tokens are common.
    cost_input = total_input_tokens * cost_input_token
    cost_output = total_output_tokens * cost_output_token
    total_cost = cost_input + cost_output

    return {
        "total_requests": int(total_requests),
        "total_input_tokens": int(total_input_tokens),
        "total_output_tokens": int(total_output_tokens),
        "total_tokens_processed": int(total_tokens),
        "cost_input_usd": cost_input,
        "cost_output_usd": cost_output,
        "total_cost_usd": total_cost,
        "duration_hours": duration_hours,
        "rps": rps
    }

if __name__ == "__main__":
    print("--- LLM Inference Cost Simulation ---")
    print(f"Simulating for {SIMULATION_DURATION_HOURS} hours at {REQUESTS_PER_SECOND} requests/second.\n")

    results = calculate_inference_cost(
        AVERAGE_PROMPT_TOKENS,
        AVERAGE_COMPLETION_TOKENS,
        REQUESTS_PER_SECOND,
        SIMULATION_DURATION_HOURS,
        COST_PER_INPUT_TOKEN,
        COST_PER_OUTPUT_TOKEN
    )

    print(f"Simulation Duration: {results['duration_hours']:.1f} hours")
    print(f"Requests Per Second (RPS): {results['rps']:.1f}")
    print(f"Average Prompt Tokens: {AVERAGE_PROMPT_TOKENS}")
    print(f"Average Completion Tokens: {AVERAGE_COMPLETION_TOKENS}\n")

    print(f"Total Requests: {results['total_requests']:,}")
    print(f"Total Input Tokens Processed: {results['total_input_tokens']:,}")
    print(f"Total Output Tokens Generated: {results['total_output_tokens']:,}")
    print(f"Total Tokens (Input + Output): {results['total_tokens_processed']:,}\n")

    print(f"Cost per Input Token: ${COST_PER_INPUT_TOKEN:.7f}")
    print(f"Cost per Output Token: ${COST_PER_OUTPUT_TOKEN:.7f}\n")

    print(f"Estimated Input Token Cost: ${results['cost_input_usd']:.2f}")
    print(f"Estimated Output Token Cost: ${results['cost_output_usd']:.2f}")
    print(f"------------------------------------")
    print(f"TOTAL ESTIMATED INFERENCE COST: ${results['total_cost_usd']:.2f}")
    print("------------------------------------")

    print("\nAdjust parameters at the top of the script to see how costs change.")
